### PR TITLE
Allow packaging of firmware

### PR DESCRIPTION
**Pull request by Canary233**

### CODE REVIEW

**Comment by anrui2032** [comment]
Ref： https://github.com/Project-Mushroom/platform_build/pull/2

**Comment by Canary233** [comment]
> Ref

Why revert?

**Comment by anrui2032** [comment]
Some device apply zip update failed

**Comment by Canary233** [comment]
> Some device apply zip update failed

Merge https://github.com/Project-Mushroom/platform_build/pull/5/commits/db7c7044f0dc7e899f6877492891e816cd48701f ？

**Comment by anrui2032** [comment]
Not only

**Comment by anrui2032** [comment]
Ref: https://review.arrowos.net/q/topic:twelve-recovery

**Comment by AmeChanRain** [comment]
Sorry for late response, will merge it with [db7c704](https://github.com/Project-Mushroom/platform_build/pull/5/commits/db7c7044f0dc7e899f6877492891e816cd48701f)

**Pull request merged**
